### ISSUE TITLE
New words to the list

### ISSUE THREAD

**Issue by Taarnborg** [stopwords-iso/stopwords-da#1]
Don't know if this repo is still being maintained, but any thoughts on including the following words?

**Forkortelser**
bl.a.
ca.
fx
f.eks.
pga.

**Nye ord**
derfra
hen

**Comment by genediazjr** [comment]
sorry for the very late response, can you provide more info why those words should be included. thanks!

**Comment by Taarnborg** [comment]
Hi @genediazjr. I had completely forgotten this issue, so no worries on the late response. 

I cannot remember why I suggested these specific words. I think it was because they kept popping up in a project I was working on back then. 

In any case, I don't know if you have a certain definition of what constitutes a stop-word? If not,  then I would think that at least the abbreviations carry very little, if any, semantic relevance for any nlp-model. 

The two last words, "derfra" og "hen", I actually don't think you should include as they are adverbials. That was a bad suggestion I think.

**Comment by genediazjr** [comment]
Yeah, I do not consider abbreviations as part of it as it can have one or more meaning.
Thank you anyway!
